name: Reusable Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      latest:
        required: true
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      packages: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/php
          tags: |
            type=raw,value=,prefix=${{ inputs.version }}
            type=sha,format=short,prefix=${{ inputs.version }}-
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=${{ inputs.version }}-
            type=raw,prefix=8,value=,enable=${{ inputs.version == inputs.latest }}
            type=raw,value=,enable=${{ inputs.version == inputs.latest }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build PHP ${{ inputs.version }}
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ inputs.version }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.version }}
          cache-to: type=gha,mode=max,scope=${{ github.event.repository.name }}-${{ inputs.version }}
          provenance: true
          sbom: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
