# This is a basic workflow to help you get started with Actions

name: Build and Push to Registry

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * 1,4
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-versions:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
  # This workflow contains a single job called "build"
  php-82:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-versions
    timeout-minutes: 720
    permissions:
      packages: write
    env:
      version: '8.2'
      alternate_version: '8'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: PHP ${{ env.version }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ env.version }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.alternate_version }}
            ghcr.io/${{ github.repository_owner }}/phpcs:latest
  php-81:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-versions
    timeout-minutes: 720
    permissions:
      packages: write
    env:
      version: '8.1'
      alternate_version: '8.1'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: PHP ${{ env.version }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ env.version }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.alternate_version }}
  php-80:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-versions
    timeout-minutes: 720
    permissions:
      packages: write
    env:
      version: '8.0'
      alternate_version: '8.0'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: PHP ${{ env.version }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ env.version }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.alternate_version }}
  php-74:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-versions
    timeout-minutes: 720
    permissions:
      packages: write
    env:
      version: '7.4'
      alternate_version: '7.4'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: PHP ${{ env.version }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            PHP_VERSION=${{ env.version }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository_owner }}/cache/phpcs:${{ env.version }}-fpm
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}-${{ needs.build-versions.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/phpcs:${{ env.alternate_version }}