# This is a basic workflow to help you get started with Actions

name: Build and Push to Registry

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * 1,4
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-versions:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

  latest:
    needs: [ build-versions, php-8 ]
    strategy:
      matrix:
        version: [ '8.2' ]
        latest: [ '8' ]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      tags: |
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.version }}-${{ needs.build-versions.outputs.date }}
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.version }}-${{ needs.build-versions.outputs.sha }}
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.version }}
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.latest }}-${{ needs.build-versions.outputs.date }}
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.latest }}-${{ needs.build-versions.outputs.sha }}
        ghcr.io/${{ github.repository_owner }}/phpcs:${{ matrix.latest }}
        ghcr.io/${{ github.repository_owner }}/phpcs:latest

  php-8:
    needs: build-versions
    strategy:
      max-parallel: 4
      matrix:
        version: [ '8.1', '8.0' ]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      tags: |
        ghcr.io/${{ github.repository_owner }}/php:${{ matrix.version }}-${{ needs.build-versions.outputs.date }}
        ghcr.io/${{ github.repository_owner }}/php:${{ matrix.version }}-${{ needs.build-versions.outputs.sha }}
        ghcr.io/${{ github.repository_owner }}/php:${{ matrix.version }}